### ISSUE TITLE
Connection error! connect ENOENT localhost You have a problem?

### ISSUE THREAD

**Issue by karthik344** [Bajdzis/vscode-database#102]
Connection error! connect ENOENT localhost You have a problem?

showing this error while connecting mysql 
![error mysql](https://user-images.githubusercontent.com/51691229/59244930-2ea0f800-8c34-11e9-9072-ee598e0fbd4c.png)

**Comment by Bajdzis** [comment]
`localhost` is not correct socket path ;) Try uncheck `via socket` option.

**Comment by karthik344** [comment]
Tried even same issue coming

**Comment by dedh121224** [comment]
![image](https://user-images.githubusercontent.com/51431260/60644037-8283b300-9e67-11e9-9f8e-726dd892e684.png)
same issue
