### ISSUE TITLE
[Feature Request] Execute inline queries

### ISSUE THREAD

**Issue by CoreyCole** [Bajdzis/vscode-database#11]
### Feature Request
Would it be possible to automatically execute single or multi-line queries? The user process I had in mind was:
1) highlight text to execute
2) press reserved key bind command (maybe alt + shift + ENTER)
3) execute `SQL: Query` command and pass the highlighted text as a parameter

I don't know anything about vscode extensions, but I could try it out. Would this feature be possible at all? Does anyone know of another extension that takes input from highlighted text?

**Comment by colinwurtz** [comment]
It looks like the [Microsoft's official extension ](https://github.com/Microsoft/vscode-mssql)for doing this with MS SQL server does exactly what you're specifying. Looking at their source code, things look quite a bit more complicated than this extension.  [This model](https://github.com/Microsoft/vscode-mssql/blob/e7e4590f9a33afb3915292bb20de9e8b440eda45/src/models/SqlOutputContentProvider.ts) seems to handle the business logic of showing the query results in a tabular format. I'm guessing it would not be trivial to port some of their logic into this extension.

**Comment by raaffaaeell** [comment]
Sorry for being late to the topic, but did you mean select the chunk of text and execute only that portion, right ?

**Comment by Torvin** [comment]
[mysql-scratchpad](https://github.com/chubtoad-black/mysql-scratchpad) can do that. But it doesn't have IntelliSense nor can save connections. Can someone please merge the two extensions?

**Comment by raaffaaeell** [comment]
@Torvin you can take a look into my fork at the branch dev-sqlite3, I added this functionality at the runquerybuild file and added a command (ctrl+enter) for it
