### ISSUE TITLE
MySQL 8.0.17 ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client You have a problem?

### ISSUE THREAD

**Issue by 97krihop** [Bajdzis/vscode-database#115]
ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
You have a problem?
MySQL ver:8.0.17

**Comment by Bajdzis** [comment]
https://github.com/Bajdzis/vscode-database/issues/104
