### ISSUE TITLE
can't connet mysql through vs code

### ISSUE THREAD

**Issue by ArrianGuo** [Bajdzis/vscode-database#147]
when I use vs code to connect to MySQL  server, it showed as below
![image](https://user-images.githubusercontent.com/30585868/68913888-caaccd80-0797-11ea-846c-5577aadf6875.png)
however, when I use other IDES, it worked well  
how?

**Comment by Bajdzis** [comment]
localhost:3306 is not valid path to file with socket ;-) You must unchecked select "via socket".

**Comment by ArrianGuo** [comment]
> localhost:3306 is not valid path to file with socket ;-) You must unchecked select "via socket".

yeah， after unselecting "via socket", it worked. thank you.

**Comment by ArrianGuo** [comment]
Ok, after unselecting “via socket”, it worked, thank you.

发件人: Rafał Budzis <notifications@github.com>
发送时间: 2019年11月16日 18:47
收件人: Bajdzis/vscode-database <vscode-database@noreply.github.com>
抄送: AriranGuo <chaoqunguo317@outlook.com>; Author <author@noreply.github.com>
主题: Re: [Bajdzis/vscode-database] can't connet mysql through vs code (#147)


localhost:3306 is not valid path to file with socket ;-) You must unchecked select "via socket".
