### ISSUE TITLE
Connection error! ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

### ISSUE THREAD

**Issue by tmonkeydev** [Bajdzis/vscode-database#149]
Was trying to connect to a server i have running. I'm using MySQL. I know my username and password are correct. Maybe it has something to do with the new security implementation by default in MySQL 8. From what i have read : 
"MySQL 8 has supports pluggable authentication methods. By default, one of them named caching_sha2_password is used rather than our good old mysql_native_password"

at this link at post 4.  
: https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server

However im not too sure if that the case or not. Just trying to give as much info as possible. Thanks in advance.

**Comment by Bajdzis** [comment]
You are right, unfortunately we are not yet supporting new mysql 8 authorization methods.

More info -> #104
