### ISSUE TITLE
Error while setting up MySQL Database in VS Code

### ISSUE THREAD

**Issue by AltairHaytham** [Bajdzis/vscode-database#189]
I've been trying to set up MySQL to VS Code for quite a while, followed many tutorials and still get this error message:

"ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client"
![VS SQL](https://user-images.githubusercontent.com/62186690/76788673-6b55dd00-67cc-11ea-8386-b31f449899bf.png)
P.S The via socket box in unchecked
      The details were filled previously, removed them for the sake of uploading here :)
Would really appreciate some help.

**Comment by Bajdzis** [comment]
Unfortunately, the new authorization system (MySQL 8) is not supported. 

More info -> #104
