### ISSUE TITLE
Clicking outside VSCode...`

### ISSUE THREAD

**Issue by blitzd** [Bajdzis/vscode-database#19]
Clicking out of VSCode when you are setting up a new database connection causes the prompt to switch. I.e., I have a long AWS connection string that I wish to use and I don't want to type it all out, so I'm copying it - but when I click outside of the window it changes from 'localhost' (where it's asking for the sever name) to 'postgres' (where it's asking for the database name). 

So, there's no way to copy/paste db info in via the interface.

**Comment by Bajdzis** [comment]
Problem with clicking outside the prompt is caused by VSCode. Plugin cant't fix it.

**Comment by ilmam** [comment]
Where are the connection setting saved, so that we can edit it later? This is related because like @blitzd I can't manage to copy past complex passwords for example.

**Comment by adam-p** [comment]
I have this problem as well -- I need to paste both the DB hostname and the password, but the prompt disappears when I got to copy the latter.

Perhaps the `host` prompt could accept something like a `username:passsword@host` format?

**Comment by leerssej** [comment]
I had the same problem, but found I could edit the file by clicking on the elephant head in a jar icon (PostgreSQL in a DB Drum) near the bottom of the icon menu along the left border. (below the Extensions Icon)

**Comment by Bajdzis** [comment]
I created new connection form based on WebView. What do you think?

@blitzd @ilmam @adam-p @leerssej 

![new-form](https://github.com/Bajdzis/vscode-database/raw/master/readme/v2.0-connection.gif)
