### ISSUE TITLE
Error opening connection ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

### ISSUE THREAD

**Issue by hfenelsoftllc** [Bajdzis/vscode-database#197]
DEBUG: Settings updated!
INFO: Executing SQLTools.getConnectionStatus
DEBUG: Settings updated!
INFO: Executing SQLTools.getConnectionStatus
DEBUG: Settings updated!
INFO: Executing SQLTools.getConnectionStatus
DEBUG: Settings updated!
INFO: Executing SQLTools.getConnectionStatus
INFO: Executing SQLTools.getConnectionStatus
DEBUG: Settings updated!
INFO: Executing SQLTools.getConnectionStatus
INFO: Executing SQLTools.getConnectionStatus
DEBUG: Settings updated!
INFO: Executing SQLTools.getConnectionStatus
DEBUG: Settings updated!
INFO: Executing SQLTools.getConnectionStatus
DEBUG: Settings updated!
INFO: Executing SQLTools.getConnectionStatus
DEBUG: Settings updated!
INFO: Executing SQLTools.getConnectionStatus
DEBUG: Settings updated!
INFO: Executing SQLTools.getConnectionStatus
DEBUG: Settings updated!
INFO: Executing SQLTools.getConnectionStatus
INFO: Executing SQLTools.selectConnection
INFO: Executing SQLTools.selectConnection
INFO: Executing SQLTools.openAddConnectionScreen
INFO: Executing SQLTools.addConnection
INFO: Executing SQLTools.getConnectionStatus
DEBUG: Settings updated!
INFO: Executing SQLTools.getConnectionStatus
DEBUG: Connection explorer updated.
INFO: Executing SQLTools.selectConnection
INFO: Executing SQLTools.showOutputChannel

**Comment by Bajdzis** [comment]
Unfortunately, the new authorization system (MySQL 8) is not supported. SQLTools is other extension -> https://github.com/mtxr/vscode-sqltools

More info -> #104
