### ISSUE TITLE
MySQl plugin erro

### ISSUE THREAD

**Issue by Bowwowgab** [Bajdzis/vscode-database#198]
I have installed MySQL on my laptop but can't connect it using local host port. i have plugin MySQl connector but it doesn't work with Visual Code any help

Error opening connection ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

**Comment by harveechen** [comment]
the same

**Comment by Bajdzis** [comment]
@Bowwowgab @harveechen 

Unfortunately, the new authorization system (MySQL 8) is not supported. 

More info -> #104
