### ISSUE TITLE
Having Problem

### ISSUE THREAD

**Issue by NiloyKumarKundu** [Bajdzis/vscode-database#199]
I can't connect with my localhost. when I try to connect to my localhost, then I got this error
Connection error! ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
You have a problem? 

How to solve this error!

**Comment by Bajdzis** [comment]
Unfortunately, the new authorization system (MySQL 8) is not supported. 

> How to solve this error!

You can temporarily change user authorization to mysql_native_password !
In this authentication system, the plugin works correctly.

More info -> #104
