### ISSUE TITLE
Randomly adds empty last.sql and temp.sql files to projects not even using sql

### ISSUE THREAD

**Issue by codingthat** [Bajdzis/vscode-database#20]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:01:14.464Z)
- OS Version: Linux x64 4.4.0-53-generic
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|vscode-database|bajdzis|1.2.0|
|vshaxe|nadako|1.5.0|;

![vscode tempsql](https://cloud.githubusercontent.com/assets/26723818/25175696/120bc612-24fc-11e7-8d77-5fd9685d1efa.png)

Sometimes one, sometimes the other, sometimes both, sometimes none.  Pretty sure it's related to this extension, given the name.

**Comment by HRK44** [comment]
Still having this issue

**Comment by Bajdzis** [comment]
Duplicate #59
