### ISSUE TITLE
Query not showing results, possibly too many rows

### ISSUE THREAD

**Issue by raaffaaeell** [Bajdzis/vscode-database#21]
Hello, nice extension, appreciate the work

I have a task that saves about 600 rows in a table, whenever I try to select all the rows with select * from table it doesnt show nothing

I tried limiting the number of rows and I could see 400 rows, past that it didnt work.

If it helps, this table has 6 fields

Cheers

Edit: Was debuging this extension and got the message "Output omitted for a large object that exceeds the limits"

Anyone knows how to deal with this ? I dont care if the output is too big

Edit2: Found out in the vscode source that it has a const of MAX_LENGTH for these kind of inputs and the value is 100000. What I was trying to do debugging/testing was to create a new untitled file and paste the results in the editor

This is the code I used

var doc = vscode.window.activeTextEditor.edit(e => {
                e.insert(new vscode.Position(0, 0), msg);
            });

it's nothing fancy and I'm sure that somebody more skilled would know how to open a new texteditor and then put the message in. Could be a fix

Another fix I tried was splitting the output into pieces of MAX_LENGTH size then appending them in the outputchannel. It worked but I had to change the "scrollback" to something like 9999999999 to be able to scroll and see the result in the output channel.

**Comment by Bajdzis** [comment]
Could you send SQL file with this table and failed query ? Thanks ;)

**Comment by raaffaaeell** [comment]
I attached the mysqldump of the table


[annotations.zip](https://github.com/Bajdzis/vscode-database/files/1033882/annotations.zip)
