### ISSUE TITLE
Create new connection

### ISSUE THREAD

**Issue by ProtocolLive** [Bajdzis/vscode-database#211]
Got this error when create new connection:
ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

**Comment by DarkKnight1005** [comment]
same

**Comment by Bajdzis** [comment]
@ProtocolLive  @DarkKnight1005 

Unfortunately, the new authorization system (MySQL 8) is not supported. 

More info -> #104
