### ISSUE TITLE
issue for send config insecureAuth ?

### ISSUE THREAD

**Issue by spham** [Bajdzis/vscode-database#216]
Hi

I wish to send insecureAuth, but dont get how to do this ?

Connection error! MySQL server is requesting the old and insecure pre-4.1 auth mechanism. Upgrade the user password or use the {insecureAuth: true} option.

**Comment by Bajdzis** [comment]
In the new version (2.2.3) I added a checkbox that allows for insecureAuth. 
I hope this helps you at work :)
