### ISSUE TITLE
ER_NOT_SUPPORTED_AUTH_MODE: 

### ISSUE THREAD

**Issue by astroanax** [Bajdzis/vscode-database#219]
When i try to connect to MySQL server, i get this error:
Connection error! ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
How can i get rid of this?
Edit: SORRY!, fixed by https://stackoverflow.com/a/50547109/13213725

**Comment by Bajdzis** [comment]
No problem :) I wait for support new auth in node js :/ 

https://github.com/mysqljs/mysql/pull/2233

https://github.com/Bajdzis/vscode-database/issues/104
