### ISSUE TITLE
ER_NOT_SUPPORTED_AUTH_MODE

### ISSUE THREAD

**Issue by luizfelipec** [Bajdzis/vscode-database#226]
Não cosigo conectar o vscode no mysql. Como poderia resolver esse problema? Toda vez que tento conctar recebo a seguinte mensagem 'Connection error! ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
You have a problem?'

**Comment by Bajdzis** [comment]
Unfortunately, the new authorization system (MySQL 8) is not supported.

More info -> #104
