### ISSUE TITLE
ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

### ISSUE THREAD

**Issue by raoziqiang** [Bajdzis/vscode-database#229]
ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

what‘s this？

**Comment by Bajdzis** [comment]
Unfortunately, the new authorization system (MySQL 8) is not supported.

More info -> #104
