### ISSUE TITLE
How to change default port ?

### ISSUE THREAD

**Issue by Perterually** [Bajdzis/vscode-database#25]
I want to change default port to 3307.  What should i do ?  Thanks you.

**Comment by k--kato** [comment]
@Perterually You can change default port to `host:port`.
```bash
localhost:3307
```

**Comment by ecbrodie** [comment]
It would be better UX when setting up my SQL connection to have an additional prompt for the port number if I did not provide it after the `:` character for the `host`. It can also have the default port number in parentheses, with entering a blank means that the default port is used.

I'll PR something in for this.

**Comment by Perterually** [comment]
Thank you.

**Comment by Bajdzis** [comment]
@ecbrodie Add only new example.

**Comment by ecbrodie** [comment]
Not sure what you mean by this. Regardless, I guess I haven't been affected by this bug due to my low usage of this plugin. Perhaps no one else felt the pain I had 3 months ago.
