### ISSUE TITLE
Connection error! ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

### ISSUE THREAD

**Issue by will-fsanches** [Bajdzis/vscode-database#266]
Connection error! ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

**Comment by ghost** [comment]
I also encountered the same problem, my MySQL version is 8.0

**Comment by Bnjoroge1** [comment]
https://stackoverflow.com/questions/50093144/mysql-8-0-client-does-not-support-authentication-protocol-requested-by-server

**Comment by Bajdzis** [comment]
@will-fsanches  @Apollo-XIII  @Bnjorogedev 

Unfortunately, the new authorization system (MySQL 8) is not supported.

More info -> #104
