### ISSUE TITLE
Connection error! ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

### ISSUE THREAD

**Issue by swopr** [Bajdzis/vscode-database#275]
MySQL server is running on a docker container with a standard image pulled from docker hub
mysql/mysql-server:latest

sh-4.2# mysqld --version
/usr/sbin/mysqld  Ver 8.0.22 for Linux on x86_64 (MySQL Community Server - GPL)

**Comment by Bajdzis** [comment]
Unfortunately, the new authorization system (MySQL 8) is not supported.

More info -> #104
