### ISSUE TITLE
Error trying to connect to SQL server in Visual Studio Code

### ISSUE THREAD

**Issue by oacevedo12** [Bajdzis/vscode-database#280]
Connection error! ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

**Comment by ngfizzy** [comment]
I am experiencing this too

**Comment by Bajdzis** [comment]
@oacevedo12 @ngfizzy 

Unfortunately, the new authorization system (MySQL 8) is not supported.

More info -> #104
