### ISSUE TITLE
Empty database.json created every time when opening a folder

### ISSUE THREAD

**Issue by markus-wa** [Bajdzis/vscode-database#34]
Every time I open a folder with this plugin enabled it creates the `.vscode` folder (if it doesn't exist) and an empty (`{}`) `database.json` file inside it.

This is slightly annoying, especially since I prefer having no VSCode metadata inside my projects.

**Comment by PascalTurbo** [comment]
+1

**Comment by Bajdzis** [comment]
ok i start work at change my file setting to VS Code setting ;)
