### ISSUE TITLE
Can someone please provide syntax of setting.json file

### ISSUE THREAD

**Issue by psabuwala** [Bajdzis/vscode-database#45]
I am a new user of this extension,
Can someone provide me the syntax for MySQL connection?
"database.connections": []

**Comment by palexander** [comment]
Here is an example of the User Settings file without any settings besides the vscode-database. Options for the `type` settings are `mysql` or `postgres`.

```json
{
    "database.connections": [
        {
            "type": "postgres",
            "name": "your name",
            "user": "your user",
            "host": "example.com:5432",
            "password": "your-password",
            "database": "your_database"
        }
    ]
}
```

**Comment by Fenweldryn** [comment]
Thanks! Would be nice to add that to the readme.

**Comment by saileshkush95** [comment]
How to setup postgres and mysql database in workspace setting

**Comment by Bajdzis** [comment]
You can use command `SQL: Save current server`. In future i add icon to save this setting ;)

**Comment by Ben-Cox** [comment]
The workspace setting above didn't work for me, 
Where do i execute the `SQL: Save current server command` ?  I cant figure out how to save server 
settings in a workspace.  I keep having to connect manually.

I also tried a keyboard shortcut to exectute saveConfig but it didnt seem to do anything either. I'm really new to vscode and postgres so any help would be appreciated.

> 
> 
> You can use command `SQL: Save current server`. In future i add icon to save this setting ;)

A button would be great for this.

**Comment by Bajdzis** [comment]
@Ben-Cox Use shortcut (Ctrl + Shift + P) and find `SQL: Save current server` command.

> A button would be great for this.

You right! I created issue #77
