### ISSUE TITLE
How can I see results inside the query file instead of OUTPUT console

### ISSUE THREAD

**Issue by boobo94** [Bajdzis/vscode-database#48]
I want to know how can I see the results inside a file, as in your gif. Right now I can see them just in the console, but looks weird

`SELECT * FROM accounts

ROW : 0

 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | id         | 1                                                                                                                                                                          | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | created_at | Thu May 24 2018 18:58:21 GMT+0300 (EEST)                                                                                                                                   | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | updated_at | Thu May 24 2018 18:58:21 GMT+0300 (EEST)                                                                                                                                   | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | deleted_at | null                                                                                                                                                                       | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | email      | dsad                                                                                                                                                                       | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | password   | $2a$10$l5LiQ2IyoY5bwTnWlTCAE.Rp.zojYWGEnYOHgTmpF3ppJqOmF1kmK                                                                                                               | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | role       | admin                                                                                                                                                                      | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | token      | 682e7084032f81f99ecf4b3894555f41                                                                                                                                           | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

ROW : 1

 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | id         | 2                                                                                                                                                                          | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | created_at | Thu May 24 2018 18:58:34 GMT+0300 (EEST)                                                                                                                                   | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | updated_at | Thu May 24 2018 18:58:34 GMT+0300 (EEST)                                                                                                                                   | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | deleted_at | null                                                                                                                                                                       | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | email      | dsad                                                                                                                                                                       | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | password   | $2a$10$4kNOv2TDSHPH8LIh2oGcy.P45lKCc/i2zcFkx5PgncMI2ism4mw3O                                                                                                               | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | role       | admin                                                                                                                                                                      | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | token      | 7c64845b975b754f538d50506664da53                                                                                                                                           | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

ROW : 2

 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | id         | 3                                                                                                                                                                          | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | created_at | Fri May 25 2018 10:20:28 GMT+0300 (EEST)                                                                                                                                   | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | updated_at | Fri May 25 2018 10:20:28 GMT+0300 (EEST)                                                                                                                                   | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | deleted_at | null                                                                                                                                                                       | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | email      | dsad                                                                                                                                                                       | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | password   | $2a$10$XqoDqZvfDtVlZHvQPebsXObdD6YRhXIKz0yEUPHs423nmK3jsEACy                                                                                                               | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | role       | admin                                                                                                                                                                      | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | token      | d340c550d696051364f4f2a9110672f2                                                                                                                                           | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

ROW : 3

 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | id         | 4                                                                                                                                                                          | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | created_at | Fri May 25 2018 10:21:33 GMT+0300 (EEST)                                                                                                                                   | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | updated_at | Fri May 25 2018 10:21:33 GMT+0300 (EEST)                                                                                                                                   | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | deleted_at | null                                                                                                                                                                       | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | email      | dsad                                                                                                                                                                       | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | password   | $2a$10$O1NPl68shP3i56EvcOUM8Oe61qKqgeHXb/nVMPofzqKqbxg8IT60m                                                                                                               | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | role       | admin                                                                                                                                                                      | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
 | token      | 4fefbc4bbba414051b1a8a509e38fade                                                                                                                                           | 
 +------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
`
It is happen on both dialects mysql and postgres for tables with multiple columns. I saw that for tables with less than 3-4 columns it's render correctly the output.

I think it's important to know that I'm using a laptop with 13" display.

**Comment by Bajdzis** [comment]
Since version 2.0.3 have a new view based on markdown ;)
