### ISSUE TITLE
disregard the commented code

### ISSUE THREAD

**Issue by sergionader** [Bajdzis/vscode-database#51]
Hey, thanks for your hard work. I am very happy with this extension. 

As a suggestion, it would be great if the extension will disregard comment code. 
For instance, if I try to run
```
-- select count(id) from users; 
select * from users; 
``` 
I will get a syntax error. Same thing if the comment is in this fomat: `/*  select count(id) from users;  */`

I also tried to select what I want to be executed before doing so with no success. 

Thanks!

Sergio

**Comment by Bajdzis** [comment]
Fixed in 2.2.0 version
