### ISSUE TITLE
CTRL+ENTER on Git sidebar creates temp.sql

### ISSUE THREAD

**Issue by luisnabais** [Bajdzis/vscode-database#59]
Hello.

If I press CTRL+ENTER on the Git sidebar screen, with vscode-database extension enabled, it creates a temp.sql file.

Is that an issue/bug? if it is, please fix it, or enable a way to fix the keyboard shortcut.

Thanks a lot

**Comment by horsley** [comment]
quite alloying

**Comment by abishekaditya** [comment]
Adding to this, the ability to commit itself is removed for me with CMD+ENTER
