### ISSUE TITLE
[bug] change database in postgres

### ISSUE THREAD

**Issue by Bajdzis** [Bajdzis/vscode-database#66]
@Bajdzis, So the first issue is fixed. I no longer see the error message.

But the second issue is still here. I can't connect to the database. I see "Database not selected":

![db-vscode](https://user-images.githubusercontent.com/3975738/53838615-32224480-3f9e-11e9-8473-f66d7d121377.gif)

Also in VS Code dev tools, I see the following error message:
![image](https://user-images.githubusercontent.com/3975738/53838653-449c7e00-3f9e-11e9-8317-4dfe70a5ad31.png)

Looks like `this.connection` is null here:

https://github.com/Bajdzis/vscode-database/blob/d653a2f33a845669a570a8edb89d99842f26bb08/extension/engine/postgresql.js#L149

I can try to dig in deeper but I'll have to set up dev env for this. Let me know if you don't have time and want me to try.

---
I think this is a separate issue so you may want to close this and open a new one.

_Originally posted by @RomanGotsiy in https://github.com/Bajdzis/vscode-database/issues/63#issuecomment-469865164_

**Comment by Bajdzis** [comment]
@RomanGotsiy Fixed and tested in 2.0.2 version ;)

**Comment by RomanGotsiy** [comment]
I can confirm it works now 🎉 

Thanks @Bajdzis for the quick fix 🙏
