### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Omokiti** [Bajdzis/vscode-database#75]
- Issue Type: `Performance`
- Extension Name: `vscode-database`
- Extension Version: `2.0.3`
- OS Version: `Windows_NT x64 10.0.17134`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `C:\Users\Emamuzo\bajdzis.vscode-database-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by Bajdzis** [comment]
How many connections do you have saved in `database.connections` in vscode settings?
