### ISSUE TITLE
Connection error! Received packet in the wrong sequence.

### ISSUE THREAD

**Issue by crazywook** [Bajdzis/vscode-database#78]
It was working at yesterday
But Today extention make 
![스크린샷 2019-03-18 오전 11 01 17](https://user-images.githubusercontent.com/23446473/54502565-9c5bc180-496e-11e9-894c-591482d65e7a.png)

I try to with port localhost:3306

My project connect to Mysql with localhost well

**Comment by JaPawel** [comment]
Same here - on v2.1.x. Downgrading to v2.0.3 helps.

**Comment by crazywook** [comment]
> Same here - on v2.1.x. Downgrading to v2.0.3 helps.

Thank you for reply. It works well

**Comment by ocamachor** [comment]
and how do I install version 2.0.3?   **Help** !

**Comment by JaPawel** [comment]
@ocamachor in Extensions pane search for this extension, and then click `Manage` (gear icon), then `Install Another Version...`, finally choose version from the list. Also disable auto update in settings `"extensions.autoUpdate": false`

<img width="622" alt="e" src="https://user-images.githubusercontent.com/8151020/54533474-8cea7180-498a-11e9-84be-98ba2c23269c.png">

<img width="637" alt="list" src="https://user-images.githubusercontent.com/8151020/54533544-ba371f80-498a-11e9-8f78-7653d230610d.png">

**Comment by Bajdzis** [comment]
I started using webpack since version 2.1.0. It is possible that webpack is causing the bug. I have found some similar bugs : 

https://github.com/mysqljs/mysql/issues/1548

https://github.com/webpack/webpack/issues/3150

I will try to fix it today.

@crazywook @JaPawel  @ocamachor

**Comment by Bajdzis** [comment]
Fixed in v2.1.3 ;)

**Comment by ocamachor** [comment]
for when v2.1.3 ?

PDTA:  Thanks to everyone for your replies!
