### ISSUE TITLE
Multiple connections to same database: error packets received in wrong sequence

### ISSUE THREAD

**Issue by lyndhurst** [Bajdzis/vscode-database#79]
Hi, I am using vscode 1.32.3 on kubuntu 18.04.

I have used your extension for a few days on a local mysql db for development with no problems.
I had only one saved connection as database admin. After creating a new user on my mysql server, I tried adding this new connection through the extension. 

From there, vscode-database keeps throwing 'packets received in wrong sequence' error. I cannot use any of the previously set connections.

I tried uninstalling the extension, removing its folder completely, and removing the 'database connection' bit in the project folder json file.

It had no effect, every time I reinstall the extension, I get the same error message right after install, and, trying to add a new connection through palette command throws an error too, and, kindly offers me a link to post an issue; so here I am )

Your extension is a great addition to my workflow, and adding the icon on the sidebar makes a cleaner IDE to my taste, so even though I am using an alternative at the moment,  I am looking forward to using it again. Thank you for your contribution.

**Comment by Bajdzis** [comment]
I started using webpack since version 2.1.0 (1 day ago). It is possible that webpack is causing the bug. I have found some similar bugs : 

https://github.com/mysqljs/mysql/issues/1548

https://github.com/webpack/webpack/issues/3150

I will try to fix it today.

@lyndhurst Thanks for the issue and detailed description of the error. if you need to use an extension today, you can downgrade it to version 2.0.3

**Comment by Bajdzis** [comment]
Duplicate #78

**Comment by lyndhurst** [comment]
Thank you for your quick reply.
I will try downgrading, and I will follow the progress on #78  .
Good luck for this fix.

**Comment by Bajdzis** [comment]
Fixed in v2.1.3 ;)

**Comment by lyndhurst** [comment]
I know the issue is closed, but I always feel bad about posting only when things go wrong.
I did not have time to try your fix out before, it works like a charm on Kubuntu 18.04 .
Thank you for your time.
