### ISSUE TITLE
commands not found on OSX

### ISSUE THREAD

**Issue by bjsion** [Bajdzis/vscode-database#8]
Hi Devs,

Not sure if the issue is on my end or not. I have tried to install the the plugin. When I tried to connect to my Postgres DB I got the following error:

command 'extension.connectPostgreSQL' not found

I also get similar errors for other commands.

Environment:
OS: OSX Sierra 10.12.1
VSCode: 1.7.1

Let me know if you need more details

**Comment by Bajdzis** [comment]
duplicate #7

**Comment by bjsion** [comment]
Thanks @Bajdzis its working now. Keep up the great work.
