### ISSUE TITLE
Client does not support authentication protocol requested by server

### ISSUE THREAD

**Issue by liuyl1992** [Bajdzis/vscode-database#81]
Connection error! ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client
You have a problem?

**Comment by liyang85** [comment]
I have the same error: `Connection error! ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client`. Would you like to help fixing it? Thanks.

MySQL Server version: 8.0.15 (installed by Homebrew)

**Comment by memehuezo** [comment]
Connection error! ER_NOT_SUPPORTED_AUTH_MODE: Client does not support authentication protocol requested by server; consider upgrading MySQL client

**Comment by Bajdzis** [comment]
@liuyl1992 @liyang85 @RyanZhiNie @memehuezo 

You can temporarily change user authorization to  `mysql_native_password` .

https://github.com/Bajdzis/vscode-database/issues/104
