### ISSUE TITLE
Extension error when query returns NULL values and a Markdown preview is generated

### ISSUE THREAD

**Issue by EPMatt** [Bajdzis/vscode-database#86]
The extension halts whenever a command which requires a Markdown preview of the query is executed, and the result set contains **NULL values**.
It can be checked by typing in a file `SELECT NULL`, then running that script with the command **SQL: Run file as query**, the extension would not generate the Markdown preview.

**Comment by Bajdzis** [comment]
Fixed in 2.1.5 version
