### ISSUE TITLE
command 'extension.connectMySQL' not found

### ISSUE THREAD

**Issue by wzup** [Bajdzis/vscode-database#9]
Seems it doesn't work

vscode-database: v1.0.10
vscode: v1.7.1
node: 6.5.0
OS: windows 10

![visual studio code 2016-11-19 00 57 45](https://cloud.githubusercontent.com/assets/3880497/20438707/8113979a-adf3-11e6-96e6-104d19cd8cbc.png)

![visual studio code 2016-11-19 00 58 39](https://cloud.githubusercontent.com/assets/3880497/20438710/8668d6e2-adf3-11e6-9257-29d461152f34.png)

![visual studio code 2016-11-19 01 12 18](https://cloud.githubusercontent.com/assets/3880497/20439190/7596ede8-adf5-11e6-934e-c3a60f72d954.png)

**Comment by Bajdzis** [comment]
duplicate #7
