### ISSUE TITLE
ER_WRONG_FIELD_WITH_GROUP when attempting to connect

### ISSUE THREAD

**Issue by ahaverty** [Bajdzis/vscode-database#92]
I'm suddenly getting this error when trying to connect to any of my databases:

> Error while preparing columns completions for connection redacted-Develop Core ER_WRONG_FIELD_WITH_GROUP: Expression #4 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'information_schema.f.ROUTINE_NAME' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by Would you like to see the logs?

MySQL 5.7
Google Cloud SQL

Global settings:
```json
"sqltools.connections": [
    {
      "askForPassword": false,
      "connectionTimeout": 30,
      "database": "core",
      "dialect": "MySQL",
      "name": "REDACTED Core",
      "password": "REDACTED",
      "port": 3306,
      "server": "REDACTED",
      "username": "REDACTED"
    },
    {
      "askForPassword": false,
      "connectionTimeout": 30,
      "database": "core",
      "dialect": "MySQL",
      "name": "REDACTED Core",
      "password": "REDACTED",
      "port": 3306,
      "server": "REDACTED",
      "username": "REDACTED"
    }
  ]
```

The only recent change I've made to the database is dropping the core database and creating it again with collation: `utf8mb4_general_ci`

**Comment by Bajdzis** [comment]
Hi! My extension use `database.connections` key in VS Code setting. You probably use other SQL extension for VS Code. Start using my extension or write issue in another repository ;)

**Comment by ahaverty** [comment]
Oh god 😅 sorry!

**Comment by ahaverty** [comment]
I found it 😅 
(link in case google brings anyone here) https://github.com/mtxr/vscode-sqltools/issues/176
Apologies again!

**Comment by Bajdzis** [comment]
You have no reason for Apologize! I'm happy you've solved your problem :)
